#!/bin/bash

# First - ensure any changes to the Java are compiled up
if ! ant; then
    exit 1
fi

# An Example shell script for launching Synthon from the command line.
# This will work on Linux or OSX

# Note that we give the JVM 12 gig of memory. This is enough for very complex
# renders, you should be able to use a lot less, especially if less 
# parallelism is used.
# -XX:+UseCompressedOops \
# -XX:+UseCompressedKlassPointers \
# -XX:+PrintCompilation \

java \
    -XX:+UseCompressedOops \
    -XX:+UseCompressedClassPointers \
    -DsonicFieldTemp=/tmp \
    -Dsython.threads=8 \
    -Xmx1G \
    -Dsython.linear=false \
    -Dsython.trace=false \
    -Dsython.modules=/Users/alexanderturner/SonicFieldRepo/SonicField/src/com/nerdscentral/sython/modules \
    -XX:+UseParallelGC \
    -Dsython.steal=true \
    -DsonicFieldDirectMemory=true \
    -XX:MaxDirectMemorySize=11g \
    -XX:MaxInlineSize=128 \
    -XX:InlineSmallCode=1024 \
    -Xms128m \
    -classpath bin:jars/jython-standalone-2.7.0.jar com.nerdscentral.sython.Sython $1

# To run on Windows simply copy this file to a batch file and put all the class path on 
# one line separated by ; rather than :
